export enum SettingsKey {
    APP_SETUP = 'APP_SETUP',
    COMPANY_NAME = 'COMPANY_NAME',
    COMPANY_IMAGE = 'COMPANY_IMAGE',

    REGISTRATION_ENABLED = 'REGISTRATION_ENABLED',
    MONTHLY_INVOICE_EMAIL_REMINDER_ENABLED = 'MONTHLY_INVOICE_EMAIL_REMINDER_ENABLED',
}