name: Enforce PR Title Format

on:
  pull_request:
    types: [opened, edited]
    branches:
      - prod

jobs:
  check_pr_title_format:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title Format
        id: check_title
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ ! "$title" =~ ^Release[[:space:]]v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Pull request title must be in the format 'Release v0.0.0', where each '0' is a digit."
            exit 1
          fi
